--1. What is the total revenue generated by male vs. female customers?
SELECT gender, SUM(purchase_amount) as revenue
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
GROUP BY gender;


--2. Which customers used a discount but still spent more than average purchase amount?
SELECT customer_id, purchase_amount
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
WHERE discount_applied = TRUE
  AND purchase_amount >= (
      SELECT AVG(purchase_amount)
      FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
  );


--3. Which are the top 5 products with the highest average review rating?
SELECT item_purchased, ROUND(AVG(review_rating), 2) as `Average Product Rating`
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
GROUP BY item_purchased
ORDER BY avg(review_rating) DESC
LIMIT 5;


--4. Compare the average purchase amounts between standard and express shipping?
SELECT shipping_type, ROUND(AVG(purchase_amount), 2)
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
WHERE shipping_type IN ('Standard', 'Express')
GROUP BY shipping_type;


--5. Do subscribed customers spend more? Compare average spend and total revenue between subscribers and non-subscribers.
SELECT subscription_status, 
COUNT(customer_id) as total_customers, 
ROUND(AVG(purchase_amount), 2) as average_spend, 
ROUND(SUM(purchase_amount), 2) as total_spend
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
GROUP BY subscription_status
ORDER BY total_spend, average_spend DESC;


--6. Which 5 products have the highest percentage of purchases with discounts applied?
SELECT item_purchased,
ROUND(100 * SUM(CASE WHEN discount_applied = TRUE THEN 1 ELSE 0 END)/ COUNT(*), 2) as discount_rate
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
GROUP BY item_purchased
ORDER BY discount_rate DESC
LIMIT 5;


--7. Segment customers into New, Returning, and Loyal based on their total number of previous purchases, and show the count of each segment.
WITH customer_type AS (
    SELECT
        customer_id,
        previous_purchases,
        CASE
            WHEN previous_purchases = 1 THEN 'New'
            WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
            ELSE 'Loyal'
        END AS customer_segment
    FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
)

SELECT customer_segment, COUNT(*) AS `Number of Customers`
FROM customer_type
GROUP BY customer_segment;


--8. What are the top 3 most purchased products within each category?
WITH item_counts AS (
    SELECT 
      category, item_purchased,
      COUNT(customer_id) AS total_orders,
      ROW_NUMBER() OVER(partition by category ORDER BY COUNT(customer_id) DESC) as item_rank
    FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
    GROUP BY category, item_purchased
)

SELECT item_rank, category, item_purchased, total_orders
FROM item_counts 
where item_rank <= 3;


--9. Are customers who are repeat buyers (more than 5 previous purchases) also likely to subscribe?
SELECT subscription_status, COUNT(customer_id) AS repeat_buyers
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
WHERE previous_purchases >= 5
GROUP BY subscription_status;


--10. What is the revenue contribution of each group?
SELECT age_group, SUM(purchase_amount) as total_revenue
FROM `project-e0ce3b20-5369-4867-863.behavior_analysis.Customer`
GROUP BY age_group
ORDER BY total_revenue DESC;
